# Generated by Django 3.0.8 on 2021-01-12 18:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Аллерген',
                'verbose_name_plural': 'Аллергены',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Название')),
                ('proteins', models.PositiveSmallIntegerField(verbose_name='Белки')),
                ('fats', models.PositiveSmallIntegerField(verbose_name='Жиры')),
                ('carbohydrates', models.PositiveSmallIntegerField(verbose_name='Углеводы')),
                ('calories', models.PositiveSmallIntegerField(verbose_name='Калории')),
                ('price', models.DecimalField(decimal_places=2, default=100, max_digits=7, validators=[django.core.validators.DecimalValidator(12, 2), django.core.validators.MinValueValidator(0)], verbose_name='Стоимость')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('allergens', models.ManyToManyField(to='meals.Allergens', verbose_name='Аллергены')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
    ]
